### ISSUE TITLE
Never able to update A record

### ISSUE THREAD

**Issue by jessienab** [zhuwenbing/porkbun-ddns#4]
> The A update of 'myip.example.com' has failed!

I am never able to update the A record with the script, there's no extra information when adding verbosity to curl...

I just tested as well doing an update from an old IP to a new IP. API access is available...

Just wondering what the possible issue could be? Thank you.

**Comment by zhuwenbing** [comment]
Hi there! According to my past experience, this error occurs because the IP in the DNS records on Porkbun is the same as your new IP. For instance, if the IP for [myip.example.com](http://myip.example.com/) is 1.2.3.4, and your new IP is also 1.2.3.4, then when the script tries to update the IP record, it fails. Essentially, the script requires the IP on Porkbun's records to be different from your new IP in order to succeed. Since the API call to Porkbun only returns whether the update failed or succeeded without specifying this detail, the script doesn't know how to proceed. If you have any suggestions for improvement, please let me know. I hope this helps!
